### PR TITLE
[Issue#17] - Concurrent Execution of External Command

### PR DESCRIPTION
**Pull request by mccurdyc**
+ perform the external command concurrently on each external project
+ solves https://github.com/mccurdyc/neighbor/issues/17

6698c85e-7fb4-404d-8933-138224efe1e5

### CODE REVIEW

**Comment by Michionlion** [comment]
We should think about automatically determining number of concurrent workers, or adding a parameter to the config.

**Comment by mccurdyc** [comment]
100%! Yeah that was just a starting point. Should be done dynamically based on the machine. I need to dig into it a bit more because there is GOMAXPROCS go environment variable that might be useful

**Comment by mccurdyc** [comment]
this certainly needs more formal testing.

**Comment by mccurdyc** [comment]
Just found this:

"Prior to Go 1.5, GOMAXPROCS was always set to one, and usually you’d find this snippet in most Go programs:

runtime.GOMAXPROCS(runtime.NumCPU())

Almost universally, developers want to take advantage of all the cores on the machine their process is running in. Because of this, in subsequent Go versions, it is now automatically set to the number of logical CPUs on the host machine."

**Comment by mccurdyc** [comment]
im working on explicit cancellation now

**Pull request merged**
