### PR TITLE
[Issue#15] - Fix External Command Parsing

### PR DESCRIPTION
**Pull request by mccurdyc**
+ change parse command from being naive and just splitting on whitespace
+ this is definitely a work in progress, im sure we will need to tweak this
+ aims to solve Issue https://github.com/mccurdyc/neighbor/issues/15

### CODE REVIEW

**Comment by mccurdyc** [comment]
@Michionlion all great points/questions!

> Does this enable escaped "s? Do we want it to (how far down that rabbit hole do you want to go...)?

YES, it does allow escaped quotes in commands (`\"`).

> Also, I'm not sure that a command starting with `"` should be invalid... how many times do we normally use a path as the actual command? What if it has spaces it in? I'm open to suggestions/justification though! :)
as I currently understand, I still think commands starting with quotes should be invalid, but I may certainly missing something!

can you provide a/some example(s)? what do you mean by "us[ing] a path as the actual command"?

I definitely think you are on to something that should be discussed before this is merged!

---

finally, you are right, we could go very, very far down a rabbit hole on this change and that is why I think we should merge a minimal-working version and iterate as we see fit.

**Comment by Michionlion** [comment]
Well, it would not be able to parse `Program Files` as part of the executable path since there is a space. This would apply to any operating system that allows spaces in file names.

**Comment by mccurdyc** [comment]
@Michionlion great point! I will make these changes

**Comment by mccurdyc** [comment]
so the parsing started to get pretty crazy, so i felt that i was doing something wrong

I decided to take a look at how Docker handles parsing commands. the root of the parsing is [here](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/parser/parser.go#L174)

**Comment by mccurdyc** [comment]
@Michionlion so i ended up adopting Docker's [`parseWords`](https://github.com/moby/buildkit/blob/3f8ab160d5079539f9ed971fb069e4205108dd9d/frontend/dockerfile/parser/line_parsers.go#L53) function and it passes all of the tests!

I will be pushing up changes later

**Pull request merged**
